### ISSUE TITLE
shall install.sh actually be named wggl.sh?

### ISSUE THREAD

**Issue by L-U-T-i** [SuitDeer/wggl#1]
Or, shall it be `Exec=bash -c '~/wggl/install.sh'` in Wireguard.desktp? As it is now, it seems there shall also be some wggl.sh  file...

**Comment by L-U-T-i** [comment]
Nice, simple and effective script, BTW! I like it. Thanks a lot!

**Comment by SuitDeer** [comment]
> Or, shall it be `Exec=bash -c '~/wggl/install.sh'` in Wireguard.desktp? As it is now, it seems there shall also be some wggl.sh file...

The install.sh script copy itself to ~/wggl/wgl.sh 😅
