### ISSUE TITLE
conf file has no password, but Gui requires one?

### ISSUE THREAD

**Issue by beertastic** [SuitDeer/wggl#2]
I'm not that tech savy, but when I add my conf file, it asks for a password when connecting.
I however, don't use passwords on my VPN server., just limit the user to require the conf file.
how can I bypass the password requirement please?

**Comment by SuitDeer** [comment]
If you want to establish a wiregurad VPN tunnel under linux you need admin/root rights. So you need to input your root password into the password field so the wireguard application can create a new wireguard tunnel interface

**Comment by beertastic** [comment]
I've just reset my root password (and my main user also has full access to the laptop)
Both my root and my user passwords fail authentication.

Can I confirm that the ROOT user is called when creating a tunnel and that it's the ROOT users password that's expected?

If so, that's not working.

**Comment by SuitDeer** [comment]
> I've just reset my root password (and my main user also has full access to the laptop) Both my root and my user passwords fail authentication.
> 
> Can I confirm that the ROOT user is called when creating a tunnel and that it's the ROOT users password that's expected?
> 
> If so, that's not working.

Hmm...

- What operating system do you use?
- Are all the required packages installed?
```bash
sudo apt install wireguard wireguard-tools zenity resolvconf
```
- Do you find a sh script in `~/wggl/wggl.sh`?

**Comment by beertastic** [comment]
What operating system do you use?
Ubuntu 
"Linux USERNAME 6.2.0-33-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 10:33:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
"

Are all the required packages installed?
Yes
"wireguard-tools is already the newest version (1.0.20210914-1ubuntu2).
wireguard is already the newest version (1.0.20210914-1ubuntu2).
zenity is already the newest version (3.42.1-0ubuntu1).
zenity set to manually installed.
0 to upgrade, 0 to newly install, 0 to remove and 25 not to upgrade."

Do you find a sh script in ~/wggl/wggl.sh?
Yes

**Comment by SuitDeer** [comment]
Is the package "resolvconf" installed?
```bash
sudo apt install resolvconf
```

**Comment by beertastic** [comment]
Ah, it wasn't.. it is now..
Same error..
Do I need to reinstall everything, or reboot etc?

Really appreciate the help on this.. above and beyond mate!

**Comment by beertastic** [comment]
I've just reset my root password to be sure it was correct.. and it didn't help..

**Comment by SuitDeer** [comment]
On the weekend I have tested my project on a new installation of ubuntu 23.04 and I only had to install the following requirements to get it running:

```bash
sudo apt install wireguard wireguard-tools zenity resolvconf
```

Can you open a terminal an call the script manually like so?:
```bash
./~/wggl/wggl.sh
```
And send the terminal output?

**Comment by beertastic** [comment]
Ah, it says No such file..
But an ll or my home DIR clearly shows a wggl folder and a wggl.sh file in
that folder

moving to that folder and running the script direct, the Gui pops up

and in the terminal, I see this:

Base directory exists.
Wireguard.desktop exists.
wg-quick: The config file must be a valid interface name, followed by .conf

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
26/09/23,
12:32:10

**Comment by SuitDeer** [comment]
```
wg-quick: The config file must be a valid interface name, followed by .conf
```
Does your wireguard configuration file have the *.conf ending and does this file is in the folder `~/wggl`?

Does your wireguard config filename contain spaces or other special characters? If so, please rename the conf-file and only use a-zA-Z characters: `wireguardVPN.conf`

**Comment by beertastic** [comment]
Yes.
I'm using a conf file generated from my new Asus router with wireguard (and
others) as a VPN option.
Downloaded the conf fril from the router and using that, which is in the
correct folder.
Other devices work fine, it's just my ubuntu laptop.

This is not the end of the world if it's a pain, I'll happily f do a google
meet session and a screen share if it's easier though.
you've done so much already



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
26/09/23,
15:03:37

**Comment by beertastic** [comment]
I just tried connecting on a differnt WiFi network, hoping that was the issue. It was not.
Same error.
Sigh...
I'm gonna have to read the WireGuard docs aren't I ? :p
